name: Rohan Bade
tagline: Electronics, Communication and Information Engineer
career-objective: Hello! Welcome to my personal portfolio website. Below, I have mentioned my skills, certifications and achievement. You can navigate to other sections too. Thank you.
color-theme: blue # red or blue
avatar-filename: profilephoto.png # Change to your avatar's filename
url: rohanbade.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email:
    visibility: true
    mail: baderohan759@gmail.com
  github:
    visibility: true
    handle: https://github.com/RohanBade/
  linkedin:
    visibility: true
    handle: https://np.linkedin.com/in/rohan-bade
  medium:
    visibility: true
    handle: https://medium.com/@baderohan759

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  projects:
    output: true
    sort_by: year
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: year
  achievements:
    output: false
    sort_by: year

# About Page Options
collection_option:
  experience:
    label: Experience
    visibility: true
  education:
    label: Education
    visibility: true
  projects:
    label: Projects
    visibility: true
  skills:
    label: Technical Skills
    visibility: true
  publications:
    label: Publications
    visibility: true
  volunteerexperience:
    label: Volunteer Experience
    visibility: true
  certifications:
    label: Certifications
    visibility: true
  achievements:
    label: Achievements
    visibility: true

navigation:
  - title: About Me
    url: /
  - title: Education
    url: /education/
  - title: Experience
    url: /experience/
  - title: Projects
    url: /projects/
  - title: Blogs
    url: /blog/
  - title: Contact Me
    url: /contact/

include:
  - _pages

exclude:
  - readme.md
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ""
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ""
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UAâ€”XXXXXXXX-X
